import pandas as pd
from core.logger import get_logger

logger = get_logger()

class DataPreprocessor:
    def __init__(self):
        pass

    def preprocess(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Clean and preprocess the candle data.
        """
        if df is None or df.empty:
            logger.warning("Empty dataframe passed for preprocessing")
            return df
            
        try:
            # Drop rows with NaN values
            df = df.dropna()
            
            # Ensure index is datetime
            if not isinstance(df.index, pd.DatetimeIndex):
                df.index = pd.to_datetime(df.index)
                
            # Add basic time features
            df['hour'] = df.index.hour
            df['minute'] = df.index.minute
            df['day_of_week'] = df.index.dayofweek

            # Engineer ML Features using 'ta' library
            from ta.momentum import RSIIndicator
            from ta.trend import MACD, EMAIndicator
            from ta.volatility import AverageTrueRange

            # 1. RSI
            df['rsi'] = RSIIndicator(close=df['close'], window=14).rsi()
            
            # 2. MACD
            macd = MACD(close=df['close'])
            df['macd'] = macd.macd()
            df['macd_signal'] = macd.macd_signal()
            df['macd_diff'] = macd.macd_diff()
            
            # 3. EMA 50 / 200
            df['ema50'] = EMAIndicator(close=df['close'], window=50).ema_indicator()
            df['ema200'] = EMAIndicator(close=df['close'], window=200).ema_indicator()
            
            # 4. Volatility (ATR)
            df['atr'] = AverageTrueRange(high=df['high'], low=df['low'], close=df['close'], window=14).average_true_range()

            # Target Variable for ML: 1 if next close > current close, 0 otherwise
            df["target"] = (df["close"].shift(-1) > df["close"]).astype(int)

            # Drop initial NaNs generated by rolling windows
            df = df.dropna()
            
            logger.info("Successfully preprocessed data and engineered ML features", extra={"rows": len(df)})
            return df
        except Exception as e:
            logger.exception("Error during preprocessing: " + str(e))
            return df

data_preprocessor = DataPreprocessor()
